Repository esoviscode/discord-dnd-bot, pull requests merged in 2023-01, with the labels that each got.

#61 add data model
  dnd-bot/dnd_bot/logic/prototype/entity.py
Labels: enhancement

#113 delete logic/prototype/enemy.py
  dnd-bot/dnd_bot/logic/prototype/enemy.py
Labels: invalid

#118 changed map_view_message to turn_view_message
  dnd-bot/dnd_bot/dc/ui/message_templates.py
  dnd-bot/dnd_bot/dc/ui/views/view_game.py
  dnd-bot/dnd_bot/dc/ui/views/view_lobby.py
Labels: minor
